import './globals.css'
import { inter, barlow } from './fonts';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${barlow.variable} ${inter.variable} ${barlow.style.fontWeight}`}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
